# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/register
Content-Type: application/json
Accept: application/json

{
  "name": "Alice Dream",
  "dob": "1990-01-01",
  "address": "123 Example Street, Amsterdam",
  "country": "NL",
  "id_document": "ID-XYZ-123456",
  "username": "alice1213"
}

###

POST http://127.0.0.1:8000/logon
Content-Type: application/json
Accept: application/json

{
  "username": "alice1213",
  "password": "1OFxP7M!DV*K"
}

###

POST http://127.0.0.1:8000/openaccount
Content-Type: application/json
Accept: application/json

{
  "username": "alice1213",
  "password": "1OFxP7M!DV*K",
  "account_type": "saving"
}

###

GET http://127.0.0.1:8000/overview?username=alice1213
Accept: application/json