# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/register
Content-Type: application/json
Accept: application/json

{
  "name": "Alice Dream",
  "dob": "1990-01-01",
  "address": "123 Example Street, Amsterdam",
  "country": "NL",
  "id_document": "ID-XYZ-123456",
  "username": "alice1213"
}

###

POST http://127.0.0.1:8000/logon
Content-Type: application/x-www-form-urlencoded
Accept: application/json

username=alice1213&password=n5gGqeMmDVQw

###

POST http://127.0.0.1:8000/openaccount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGljZTEyMTMiLCJleHAiOjE3NTkxNjQyMzB9.za2Ar8Eeq4lsnGSkBhKR4egtF9RacLMd4vNyqqiCiT0
Content-Type: application/json
Accept: application/json

"saving"

###

GET http://127.0.0.1:8000/overview
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGljZTEyMTMiLCJleHAiOjE3NTkxNjQyMzB9.za2Ar8Eeq4lsnGSkBhKR4egtF9RacLMd4vNyqqiCiT0
Accept: application/json